version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "catalogos-747109"
resolve_s3 = true
s3_prefix = "catalogos-747109"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
